/**
 * Initializes toggle accordion interactions on a pre-built mobile menu tree.
 * Matches native class structures generated by menuBuilder.js
 * @param {HTMLElement} mobileMenuRoot - Root <ul> element
 */
export function renderMobileAccordion(mobileMenuRoot) {
  if (!mobileMenuRoot) return;

  // 1. Convert standard list classes to match BEM rules (.mobile-nav__list)
  mobileMenuRoot.classList.add('mobile-nav__list');

  // Tag all nested list elements with their respective BEM sub-classes
  mobileMenuRoot.querySelectorAll('ul').forEach((ul) => {
    ul.className = 'mobile-nav__list';
  });

  // 2. Locate all category list nodes that contain nested dropdown submenus
  const accordionItems = mobileMenuRoot.querySelectorAll(
    '.level0.parent, .has-megamenu',
  );

  accordionItems.forEach((item) => {
    item.className = 'mobile-nav__item mobile-nav__item--has-children';

    // Target the main link and the wrapper block underneath it
    const triggerLink = item.querySelector(
      ':scope > a, :scope > .ui-menu-item-wrapper',
    );
    const submenu = item.querySelector(
      ':scope > ul, :scope > .submenu, :scope > .megamenu-dropdown-panel',
    );

    if (!triggerLink || !submenu) return;

    // Convert child submenus into standard mobile panel shells safely
    submenu.className = 'mobile-nav__panel';
    submenu.style.display = 'none'; // Hidden by default

    // 3. Attach standard click listeners to manage accordion states
    triggerLink.addEventListener('click', (event) => {
      const targetHref = triggerLink.getAttribute('href');
      // If the link points to a real URL, allow it to navigate normally
      if (targetHref && targetHref !== '#') return;

      // Prevent link jump behavior for structural accordion folders
      event.preventDefault();
      event.stopPropagation();

      const isExpanded = item.getAttribute('aria-expanded') === 'true';

      // Collapse competing layout branches open on the same layer row
      const siblings = item.parentElement.children;
      Array.from(siblings).forEach((sibling) => {
        if (sibling !== item) {
          sibling.classList.remove('is-active');
          sibling.setAttribute('aria-expanded', 'false');
          const siblingSub = sibling.querySelector('.mobile-nav__panel');
          if (siblingSub) {
            siblingSub.style.display = 'none';
            siblingSub.setAttribute('aria-expanded', 'false');
          }
        }
      });

      // Toggle current target item active visibility configurations
      item.classList.toggle('is-active', !isExpanded);
      item.setAttribute('aria-expanded', !isExpanded ? 'true' : 'false');

      submenu.style.display = !isExpanded ? 'block' : 'none';
      submenu.setAttribute('aria-expanded', !isExpanded ? 'true' : 'false');
    });
  });
}

// Keep explicit named export matching your initialization script references
export { renderMobileAccordion as initMobileAccordion };
