// eslint-disable-next-line import/no-unresolved
import { toClassName } from '../../scripts/aem.js';

export default async function decorate(block) {
  // 1. Build the .tabs-list container (Flexbox wrapper with overflow-x: auto)
  const tablist = document.createElement('div');
  tablist.className = 'tabs-list';
  tablist.setAttribute('role', 'tablist');

  // Extract all block row children (each maps to an array item from _tab.json)
  const rows = [...block.children];

  rows.forEach((row, i) => {
    // According to _tab.json, the first column handles the title layout node
    const tabTitleEl = row.firstElementChild;
    if (!tabTitleEl) return;

    const id = toClassName(tabTitleEl.textContent || `tab-${i}`);

    // 2. Decorate the row as a panel container (.tabs .tabs-panel)
    row.className = 'tabs-panel';
    row.id = `tabpanel-${id}`;
    // Sets aria-hidden="true" on all except the first panel to toggle display: none
    row.setAttribute('aria-hidden', i === 0 ? 'false' : 'true');
    row.setAttribute('aria-labelledby', `tab-${id}`);
    row.setAttribute('role', 'tabpanel');

    // 3. Build the tab selection button (.tabs .tabs-list button)
    const button = document.createElement('button');
    button.className = 'tabs-tab';
    button.id = `tab-${id}`;

    // innerHTML preserves the <p> tags generated by AEM, matching: .tabs-list button p
    button.innerHTML = tabTitleEl.innerHTML;
    button.setAttribute('aria-controls', `tabpanel-${id}`);
    // First button gets aria-selected="true" to match your styling rule:
    //  button[aria-selected='true']
    button.setAttribute('aria-selected', i === 0 ? 'true' : 'false');
    button.setAttribute('role', 'tab');
    button.setAttribute('type', 'button');

    // Tab selection click handler
    button.addEventListener('click', () => {
      // Hide all panels
      block.querySelectorAll('[role="tabpanel"]').forEach((panel) => {
        panel.setAttribute('aria-hidden', 'true');
      });
      // Deselect all active buttons
      tablist.querySelectorAll('button').forEach((btn) => {
        btn.setAttribute('aria-selected', 'false');
      });

      // Show current panel and activate current button
      row.setAttribute('aria-hidden', 'false');
      button.setAttribute('aria-selected', 'true');
    });

    tablist.append(button);

    // Clean up the DOM row by extracting the title, leaving only the content element
    tabTitleEl.remove();
  });

  // 4. Prepend navigation tablist at the top of the block layout view
  block.prepend(tablist);
}
